name: untyped-lambda-calculus
version: 0.1.0.0
github: "gabrielolivrp/untyped-lambda-calculus"
license: MIT
author: "Gabriel Augusto"
copyright: "2023 Gabriel Augusto"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gabrielolivrp/untyped-lambda-calculus#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - parsec
  - haskeline
  - mtl
  - prettyprinter
  - exceptions
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  untyped-lambda-calculus-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - untyped-lambda-calculus

tests:
  untyped-lambda-calculus-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - untyped-lambda-calculus
